<?php

namespace Proxies\__CG__\moovi\MooviBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Movie extends \moovi\MooviBundle\Entity\Movie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'id', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'title', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'description', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'year', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'cover', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'slug', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'genres', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'actors', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'orders', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'comments', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'price');
        }

        return array('__isInitialized__', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'id', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'title', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'description', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'year', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'cover', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'slug', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'genres', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'actors', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'orders', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'comments', '' . "\0" . 'moovi\\MooviBundle\\Entity\\Movie' . "\0" . 'price');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Movie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setYear($year)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYear', array($year));

        return parent::setYear($year);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', array());

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setCover($cover)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCover', array($cover));

        return parent::setCover($cover);
    }

    /**
     * {@inheritDoc}
     */
    public function getCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCover', array());

        return parent::getCover();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function addGenre(\moovi\MooviBundle\Entity\Genre $genres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGenre', array($genres));

        return parent::addGenre($genres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGenre(\moovi\MooviBundle\Entity\Genre $genres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGenre', array($genres));

        return parent::removeGenre($genres);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenres', array());

        return parent::getGenres();
    }

    /**
     * {@inheritDoc}
     */
    public function addActor(\moovi\MooviBundle\Entity\Actor $actors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActor', array($actors));

        return parent::addActor($actors);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActor(\moovi\MooviBundle\Entity\Actor $actors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActor', array($actors));

        return parent::removeActor($actors);
    }

    /**
     * {@inheritDoc}
     */
    public function getActors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActors', array());

        return parent::getActors();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\moovi\MooviBundle\Entity\Order $orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', array($orders));

        return parent::addOrder($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\moovi\MooviBundle\Entity\Order $orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', array($orders));

        return parent::removeOrder($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', array());

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdersCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdersCount', array());

        return parent::getOrdersCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\moovi\MooviBundle\Entity\Comment $comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', array($comments));

        return parent::addComment($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\moovi\MooviBundle\Entity\Comment $comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', array($comments));

        return parent::removeComment($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', array());

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

}
